@BlueeitApi_HostAddress = http://localhost:5230
@BlueeitApi_Version = v1

###

GET {{BlueeitApi_HostAddress}}
Accept: application/json

###

GET {{BlueeitApi_HostAddress}}/api/{{BlueeitApi_Version}}/users
Accept: application/json

###

GET {{BlueeitApi_HostAddress}}/api/{{BlueeitApi_Version}}/users?page=2&pageSize=20
Accept: application/json

###

GET {{BlueeitApi_HostAddress}}/api/{{BlueeitApi_Version}}/users/1
Accept: application/json

###

POST {{BlueeitApi_HostAddress}}/api/{{BlueeitApi_Version}}/users
Accept: application/json
Content-Type: application/json

{
    "username": "msilva",
    "email": "marcosilva2203@outlook.pt",
    "password": "abc123"
}

###

DELETE {{BlueeitApi_HostAddress}}/api/{{BlueeitApi_Version}}/users/1
Accept: application/json

###

GET {{BlueeitApi_HostAddress}}/api/{{BlueeitApi_Version}}/threads
Accept: application/json

###

GET {{BlueeitApi_HostAddress}}/api/{{BlueeitApi_Version}}/threads?page=2&pageSize=20
Accept: application/json

###

GET {{BlueeitApi_HostAddress}}/api/{{BlueeitApi_Version}}/threads/1
Accept: application/json

###

POST {{BlueeitApi_HostAddress}}/api/{{BlueeitApi_Version}}/threads
Accept: application/json
Content-Type: application/json

{
    "authorId": 1,
    "title": "Bad Matchmaking"
}

###

POST {{BlueeitApi_HostAddress}}/api/{{BlueeitApi_Version}}/threads
Accept: application/json
Content-Type: application/json

{
    "authorId": 1,
    "title": "Cake Recipes"
}

###

DELETE {{BlueeitApi_HostAddress}}/api/{{BlueeitApi_Version}}/threads/1
Accept: application/json

###

GET {{BlueeitApi_HostAddress}}/api/{{BlueeitApi_Version}}/posts
Accept: application/json

###

GET {{BlueeitApi_HostAddress}}/api/{{BlueeitApi_Version}}/posts?page=2&pageSize=20
Accept: application/json

###

GET {{BlueeitApi_HostAddress}}/api/{{BlueeitApi_Version}}/posts/1
Accept: application/json

###

POST {{BlueeitApi_HostAddress}}/api/{{BlueeitApi_Version}}/posts
Accept: application/json
Content-Type: application/json

{
    "threadId": 1,
    "authorId": 1,
    "content": "This matchmaking is terrible!"
}

###

DELETE {{BlueeitApi_HostAddress}}/api/{{BlueeitApi_Version}}/posts/1
Accept: application/json

###
